export type SectionCopy = {
  id: string;
  eyebrow: string;
  headline: string[]; // one entry per masked line
  body?: string;
  data?: string;
  tags?: string[]; // optional badge chips shown on content card
  align: "left" | "right" | "center";
  hidden?: boolean; // timeline spacer with no visible overlay content
};

export const COPY_EN: SectionCopy[] = [
  {
    id: "hero",
    eyebrow: "AVP Biomass",
    headline: ["From Wood Waste", "to Clean Energy"],
    body: "Sustainable biomass pellets, engineered for performance and a cleaner tomorrow. Renewable energy. Responsible future.",
    tags: ["100% Renewable"],
    align: "left",
  },
  {
    id: "forest",
    eyebrow: "Sustainable forest",
    headline: ["It begins", "with nature."],
    body: "Renewable energy begins with responsibly sourced biomass.",
    data: "Forest → renewable biomass",
    tags: ["FSC 100% Certified", "Plantation Wood"],
    align: "left",
  },
  {
    id: "collection",
    eyebrow: "",
    headline: [],
    align: "left",
    hidden: true,
  },
  {
    id: "screening",
    eyebrow: "Woods chipping unit",
    headline: ["Logs become", "wood chips."],
    body: "The chipping machine reduces staged logs into controlled chips for the grinding process.",
    data: "Raw wood -> chipping -> wood chips",
    tags: ["Unit 2", "Chipping Line"],
    align: "left",
  },
  {
    id: "grinding",
    eyebrow: "Wet grinding unit",
    headline: ["Wet material", "is refined."],
    body: "Chips are ground while moisture is still present, creating a finer feedstock before temporary buffering.",
    data: "Wood chips -> wet grinding -> wet particles",
    tags: ["Unit 3", "Wet Material"],
    align: "right",
  },
  {
    id: "drying",
    eyebrow: "Buffer storage",
    headline: ["Material waits", "in balance."],
    body: "After wet grinding, the intermediate material is held in buffer storage so the downstream drying line receives a stable feed.",
    data: "Wet particles -> buffer storage",
    tags: ["Unit 4", "Flow Balancing"],
    align: "left",
  },
  {
    id: "conditioning",
    eyebrow: "Drying unit",
    headline: ["Moisture", "is controlled."],
    body: "Buffered material enters the drying unit, where moisture is reduced to the target range for stable pellet production.",
    data: "Buffered biomass -> drying -> dry biomass",
    tags: ["Unit 5", "Moisture Control"],
    align: "right",
  },
  {
    id: "pelletizing",
    eyebrow: "Recovery unit",
    headline: ["Usable material", "is recovered."],
    body: "The recovery unit separates usable dried material from dust and off-size fractions before the final grinding step.",
    data: "Dry biomass -> recovery -> clean dry feed",
    tags: ["Unit 6", "Material Recovery"],
    align: "left",
  },
  {
    id: "cooling",
    eyebrow: "Dried grinding unit",
    headline: ["Dry material", "is refined again."],
    body: "Recovered dry biomass is ground a second time to reach the particle consistency required for pelletizing.",
    data: "Recovered feed -> dried grinding -> pellet feed",
    tags: ["Unit 7", "Final Particle Size"],
    align: "right",
  },
  {
    id: "qc",
    eyebrow: "Pelletizer unit",
    headline: ["Pressure", "creates pellets."],
    body: "Prepared dry particles are compressed through the pelletizer to form dense, consistent wood pellets.",
    data: "Pellet feed -> pelletizer -> wood pellets",
    tags: ["Unit 8", "Densification"],
    align: "left",
  },
  {
    id: "packaging",
    eyebrow: "Finished product unit",
    headline: ["Finished pellets", "are completed."],
    body: "Finished wood pellets are collected as the core product of the line, ready for quality handling, storage or shipment.",
    data: "Wood pellets -> finished product",
    tags: ["Unit 9", "Core Product"],
    align: "right",
  },
  {
    id: "warehouse",
    eyebrow: "Optional upgrade path",
    headline: ["Beyond the", "core line."],
    body: "After the finished product unit, AVP can describe additional value-upgrading technology as a separate extension, not as part of the nine core units.",
    data: "Finished product -> optional upgrade",
    tags: ["Extension", "Separate From Core"],
    align: "left",
  },
  {
    id: "logistics",
    eyebrow: "Optional torrefaction",
    headline: ["Thermal treatment", "comes later."],
    body: "Torrefaction and black pellet messaging belong after the finished pellet product, as an optional advanced product route.",
    data: "Finished pellets -> torrefaction option",
    tags: ["Extension", "Thermal Treatment"],
    align: "right",
  },
  {
    id: "energy",
    eyebrow: "Black wood pellet",
    headline: ["Advanced product", "after pellets."],
    body: "Black wood pellet is presented as a downstream technology product after the regular finished wood pellet line is complete.",
    data: "Finished pellet -> upgraded pellet",
    tags: ["Advanced Product", "After Unit 9"],
    align: "left",
  },
  {
    id: "circular",
    eyebrow: "Advanced bioenergy",
    headline: ["From wood.", "To pellet.", "To higher value."],
    body: "Built from responsible resources, shaped by technology, and guided by a pioneer mindset, AVP turns biomass into higher-value advanced bioenergy.",
    data: "Responsible resources → technology → global energy value",
    tags: ["Responsible Resources", "Renewable Energy", "Global Partners"],
    align: "center",
  },
];

export const COPY_VI: SectionCopy[] = [
  {
    id: "hero",
    eyebrow: "AVP Biomass",
    headline: ["Từ Phế Thải Gỗ", "Đến Năng Lượng Sạch"],
    body: "Viên nén sinh khối bền vững, được thiết kế cho hiệu suất và một tương lai xanh hơn. Năng lượng tái tạo. Trách nhiệm với tương lai.",
    tags: ["100% Tái Tạo"],
    align: "left",
  },
  {
    id: "forest",
    eyebrow: "Rừng bền vững",
    headline: ["Bắt đầu", "từ thiên nhiên."],
    body: "Năng lượng tái tạo bắt đầu từ nguồn sinh khối được khai thác có trách nhiệm.",
    data: "Rừng → sinh khối tái tạo",
    tags: ["Chứng Chỉ FSC 100%", "Gỗ Đồn Điền"],
    align: "left",
  },
  {
    id: "collection",
    eyebrow: "",
    headline: [],
    align: "left",
    hidden: true,
  },
  {
    id: "screening",
    eyebrow: "Dăm gỗ",
    headline: ["Giảm kích thước.", "Chuẩn bị nguyên liệu."],
    body: "Gỗ được nghiền thành dăm đồng nhất, chuẩn bị nguyên liệu cho các bước xử lý tiếp theo.",
    data: "Gỗ thô → băm → dăm gỗ",
    tags: ["Băm Công Nghiệp", "Kích Thước Đồng Nhất"],
    align: "left",
  },
  {
    id: "grinding",
    eyebrow: "Mùn gỗ",
    headline: ["Tinh chế", "để đồng nhất."],
    body: "Sinh khối tiếp tục được nghiền mịn thành các hạt nhỏ hơn và đồng đều hơn.",
    data: "Dăm gỗ → nghiền → mùn gỗ",
    tags: ["Máy Nghiền Búa", "Hạt 2–4mm"],
    align: "right",
  },
  {
    id: "drying",
    eyebrow: "Sinh khối khô",
    headline: ["Kiểm soát", "độ ẩm."],
    body: "Sấy khô có kiểm soát chuẩn bị sinh khối cho quá trình nén ép hiệu quả.",
    data: "Sinh khối ướt → sấy → sinh khối khô",
    tags: ["Máy Sấy Thùng Quay", "Độ Ẩm < 10%"],
    align: "left",
  },
  {
    id: "conditioning",
    eyebrow: "Chuẩn bị",
    headline: ["Độ chính xác bắt đầu", "trước khi ép viên."],
    body: "Nguyên liệu được điều hòa để ổn định trước khi biến đổi dưới áp lực.",
    data: "Sinh khối đã chuẩn bị · sẵn sàng ép viên",
    tags: ["Điều Hòa Hơi Nước", "Lignin Tự Nhiên"],
    align: "right",
  },
  {
    id: "pelletizing",
    eyebrow: "Ép viên",
    headline: ["Áp lực", "tạo hình."],
    body: "Dưới áp lực kiểm soát, sinh khối đã chuẩn bị được biến đổi thành nhiên liệu rắn đồng nhất và chắc chắn.",
    data: "Nén → ép → viên nén",
    tags: ["Máy Ép CPM Công Nghiệp", "4.500 kcal/kg"],
    align: "left",
  },
  {
    id: "cooling",
    eyebrow: "Viên nén gỗ",
    headline: ["Năng lượng tái tạo.", "Được nén chặt."],
    body: "Sinh khối tự nhiên được biến đổi thành nhiên liệu tái tạo nhỏ gọn, đồng nhất và dễ vận chuyển.",
    data: "Kết quả của quá trình biến đổi đầu tiên",
    tags: ["Độ Bền > 97,5%", "Đường Kính 6–8mm"],
    align: "right",
  },
  {
    id: "qc",
    eyebrow: "Nâng cấp giá trị",
    headline: ["Hơn cả", "sự biến đổi."],
    body: "Hành trình tiếp tục vượt xa viên nén gỗ thông thường, bước vào một tầng giá trị mới.",
    data: "Sản phẩm → công nghệ → giá trị cao hơn",
    tags: ["Nâng Cấp Công Nghệ", "Đường Đi Giá Trị Cao"],
    align: "left",
  },
  {
    id: "packaging",
    eyebrow: "Nâng cấp nhiệt",
    headline: ["Nâng cấp những gì", "sinh khối có thể trở thành."],
    body: "Viên nén gỗ thông thường bước vào môi trường nhiệt được kiểm soát cẩn thận.",
    data: "Viên nén gỗ → nhiệt kiểm soát",
    tags: ["Nhiệt Kiểm Soát", "Xử Lý Nhiệt"],
    align: "right",
  },
  {
    id: "warehouse",
    eyebrow: "Torrefaction",
    headline: ["Công nghệ đằng sau", "sự biến đổi."],
    body: "Qua xử lý nhiệt có kiểm soát, các đặc tính bên trong của sinh khối bắt đầu thay đổi.",
    data: "Nhiệt thay đổi cấu trúc",
    tags: ["Xử Lý 250–300°C", "100% Chống Nước"],
    align: "left",
  },
  {
    id: "logistics",
    eyebrow: "Tạo giá trị",
    headline: ["Viên nén không chỉ", "sẫm màu hơn."],
    body: "Công nghệ biến đổi sản phẩm sinh khối thành vật liệu năng lượng giá trị cao hơn.",
    data: "Viên trắng → công nghệ → viên đen",
    tags: ["Nâng Cấp Vật Liệu", "Năng Lượng Giá Trị Cao"],
    align: "right",
  },
  {
    id: "energy",
    eyebrow: "Viên nén gỗ đen",
    headline: ["Sinh khối.", "Đã nâng cấp."],
    body: "Kết quả của sản xuất kết hợp công nghệ: một thế hệ năng lượng sinh khối rắn mới.",
    data: "Kết quả của quá trình biến đổi thứ hai",
    tags: ["> 5.000 kcal/kg", "Lưu Trữ Ngoài Trời"],
    align: "left",
  },
  {
    id: "circular",
    eyebrow: "Năng lượng sinh khối tiên tiến",
    headline: ["Từ gỗ.", "Đến viên nén.", "Đến giá trị cao hơn."],
    body: "Được xây dựng từ nguồn tài nguyên có trách nhiệm, định hình bởi công nghệ, và dẫn dắt bởi tư duy tiên phong, AVP biến sinh khối thành năng lượng sinh học tiên tiến giá trị cao.",
    data: "Tài nguyên trách nhiệm → công nghệ → giá trị năng lượng toàn cầu",
    tags: ["Tài Nguyên Trách Nhiệm", "Năng Lượng Tái Tạo", "Đối Tác Toàn Cầu"],
    align: "center",
  },
];

export function getCopy(locale: "en" | "vi"): SectionCopy[] {
  return locale === "vi" ? COPY_VI : COPY_EN;
}
