export type SectionCopy = {
  id: string;
  eyebrow: string;
  headline: string[]; // one entry per masked line
  body?: string;
  data?: string;
  tags?: string[]; // optional badge chips shown on content card
  align: "left" | "right" | "center";
};

export const COPY: SectionCopy[] = [
  {
    id: "hero",
    eyebrow: "AVP Biomass",
    headline: ["From wood.", "To pellet.", "To higher value."],
    body: "A journey that begins with natural biomass and evolves through technology into advanced bioenergy.",
    tags: ["2M Tons / Year", "Green Energy", "Global Export"],
    align: "center",
  },
  {
    id: "forest",
    eyebrow: "Sustainable forest",
    headline: ["It begins", "with nature."],
    body: "Renewable energy begins with responsibly sourced biomass.",
    data: "Forest → renewable biomass",
    tags: ["FSC 100% Certified", "Plantation Wood"],
    align: "left",
  },
  {
    id: "collection",
    eyebrow: "Raw wood",
    headline: ["The raw", "material."],
    body: "Selected wood resources enter the production journey.",
    data: "Acacia · wood resources · residues",
    tags: ["100% Acacia", "Clean Source"],
    align: "right",
  },
  {
    id: "screening",
    eyebrow: "Wood chips",
    headline: ["Reducing size.", "Preparing material."],
    body: "Wood is reduced into consistent chips, preparing the material for further processing.",
    data: "Raw wood → chipping → wood chips",
    tags: ["Industrial Chipping", "Uniform Size"],
    align: "left",
  },
  {
    id: "grinding",
    eyebrow: "Wood particles",
    headline: ["Refined", "for consistency."],
    body: "The biomass is further refined into smaller and more uniform particles.",
    data: "Wood chips → grinding → particles",
    tags: ["Hammer Mill", "2–4mm Particles"],
    align: "right",
  },
  {
    id: "drying",
    eyebrow: "Dry biomass",
    headline: ["Moisture", "under control."],
    body: "Controlled drying prepares the biomass for efficient densification.",
    data: "Wet biomass → drying → dry biomass",
    tags: ["Rotary Drum Dryer", "Moisture < 10%"],
    align: "left",
  },
  {
    id: "conditioning",
    eyebrow: "Preparation",
    headline: ["Precision begins", "before pelletization."],
    body: "The material is conditioned for a stable transformation under pressure.",
    data: "Prepared biomass · ready for densification",
    tags: ["Steam Conditioning", "Natural Lignin"],
    align: "right",
  },
  {
    id: "pelletizing",
    eyebrow: "Pelletizing",
    headline: ["Pressure", "creates form."],
    body: "Under controlled pressure, prepared biomass is transformed into a compact and consistent solid fuel.",
    data: "Compression → densification → pellet",
    tags: ["CPM Industrial Mill", "4,500 kcal/kg"],
    align: "left",
  },
  {
    id: "cooling",
    eyebrow: "Wood pellet",
    headline: ["Renewable energy.", "Densified."],
    body: "Natural biomass is transformed into a compact, consistent and transportable renewable fuel.",
    data: "The result of the first transformation",
    tags: ["Durability > 97.5%", "Diameter 6–8mm"],
    align: "right",
  },
  {
    id: "qc",
    eyebrow: "Value upgrading",
    headline: ["More than", "a transformation."],
    body: "The journey continues beyond conventional wood pellets into a new layer of value.",
    data: "Product → technology → higher value",
    tags: ["Technology Upgrade", "Higher-Value Path"],
    align: "left",
  },
  {
    id: "packaging",
    eyebrow: "Thermal upgrading",
    headline: ["Upgrading what", "biomass can become."],
    body: "Conventional wood pellets enter a carefully controlled thermal environment.",
    data: "Wood pellet → controlled heat",
    tags: ["Controlled Heat", "Thermal Treatment"],
    align: "right",
  },
  {
    id: "warehouse",
    eyebrow: "Torrefaction",
    headline: ["The technology behind", "the transformation."],
    body: "Through controlled thermal treatment, the internal characteristics of biomass begin to change.",
    data: "Heat changes structure",
    tags: ["250–300°C Treatment", "100% Hydrophobic"],
    align: "left",
  },
  {
    id: "logistics",
    eyebrow: "Value creation",
    headline: ["The pellet is not", "merely darkened."],
    body: "Technology transforms an established biomass product into a higher-value energy material.",
    data: "White pellet → technology → black pellet",
    tags: ["Material Upgrade", "Higher-Value Energy"],
    align: "right",
  },
  {
    id: "energy",
    eyebrow: "Black wood pellet",
    headline: ["Biomass.", "Upgraded."],
    body: "The result of manufacturing plus technology: a new generation of solid bioenergy.",
    data: "The result of the second transformation",
    tags: ["> 5,000 kcal/kg", "Outdoor Storage"],
    align: "left",
  },
  {
    id: "circular",
    eyebrow: "Advanced bioenergy",
    headline: ["From wood.", "To pellet.", "To higher value."],
    body: "We don't just transform biomass. We create more value from it.",
    data: "Wood → pelletization → black wood pellet",
    tags: ["Advanced Bioenergy", "Higher-Value Product"],
    align: "center",
  },
];
