export type SectionCopy = {
  id: string;
  eyebrow: string;
  headline: string[]; // one entry per masked line
  body?: string;
  data?: string;
  tags?: string[]; // optional badge chips shown on content card
  align: "left" | "right" | "center";
  hidden?: boolean; // timeline spacer with no visible overlay content
};

export const COPY_EN: SectionCopy[] = [
  {
    id: "hero",
    eyebrow: "AVP Biomass",
    headline: ["From Wood Waste", "to Clean Energy"],
    body: "Sustainable biomass pellets, engineered for performance and a cleaner tomorrow. Renewable energy. Responsible future.",
    tags: ["100% Renewable"],
    align: "left",
  },
  {
    id: "forest",
    eyebrow: "Wood residue input",
    headline: ["Recovered residues", "enter the line."],
    body: "The process begins with wood residues, offcuts, bark and chips collected from responsible wood-processing sources.",
    data: "Wood residue -> receiving yard",
    tags: ["Responsible Sources", "Wood By-products"],
    align: "left",
  },
  {
    id: "collection",
    eyebrow: "",
    headline: [],
    align: "left",
    hidden: true,
  },
  {
    id: "screening",
    eyebrow: "Woods chipping unit",
    headline: ["Residues become", "controlled chips."],
    body: "The chipping machine evens out mixed wood residues into controlled chips for the grinding process.",
    data: "Wood residues -> chipping -> wood chips",
    tags: ["Unit 2", "Chipping Line"],
    align: "left",
  },
  {
    id: "grinding",
    eyebrow: "Wet grinding unit",
    headline: ["Wet material", "is refined."],
    body: "Chips are ground while moisture is still present, creating a finer feedstock before temporary buffering.",
    data: "Wood chips -> wet grinding -> wet particles",
    tags: ["Unit 3", "Wet Material"],
    align: "right",
  },
  {
    id: "drying",
    eyebrow: "Buffer storage",
    headline: ["Material waits", "in balance."],
    body: "After wet grinding, the intermediate material is held in buffer storage so the downstream drying line receives a stable feed.",
    data: "Wet particles -> buffer storage",
    tags: ["Unit 4", "Flow Balancing"],
    align: "left",
  },
  {
    id: "conditioning",
    eyebrow: "Drying unit",
    headline: ["Moisture", "is controlled."],
    body: "Buffered material enters the drying unit, where moisture is reduced to the target range for stable pellet production.",
    data: "Buffered biomass -> drying -> dry biomass",
    tags: ["Unit 5", "Moisture Control"],
    align: "right",
  },
  {
    id: "pelletizing",
    eyebrow: "Recovery unit",
    headline: ["Usable material", "is recovered."],
    body: "The recovery unit separates usable dried material from dust and off-size fractions before the final grinding step.",
    data: "Dry biomass -> recovery -> clean dry feed",
    tags: ["Unit 6", "Material Recovery"],
    align: "left",
  },
  {
    id: "cooling",
    eyebrow: "Dried grinding unit",
    headline: ["Dry material", "is refined again."],
    body: "Recovered dry biomass is ground a second time to reach the particle consistency required for pelletizing.",
    data: "Recovered feed -> dried grinding -> pellet feed",
    tags: ["Unit 7", "Final Particle Size"],
    align: "right",
  },
  {
    id: "qc",
    eyebrow: "Pelletizer unit",
    headline: ["Pressure", "creates pellets."],
    body: "Prepared dry particles are compressed through the pelletizer to form dense, consistent wood pellets.",
    data: "Pellet feed -> pelletizer -> wood pellets",
    tags: ["Unit 8", "Densification"],
    align: "left",
  },
  {
    id: "packaging",
    eyebrow: "Finished product unit",
    headline: ["Finished pellets", "are completed."],
    body: "Finished wood pellets are collected as the core product of the line, ready for quality handling, storage or shipment.",
    data: "Wood pellets -> finished product",
    tags: ["Unit 9", "Core Product"],
    align: "right",
  },
  {
    id: "warehouse",
    eyebrow: "Optional upgrade path",
    headline: ["Beyond the", "core line."],
    body: "After the finished product unit, AVP can describe additional value-upgrading technology as a separate extension, not as part of the nine core units.",
    data: "Finished product -> optional upgrade",
    tags: ["Extension", "Separate From Core"],
    align: "left",
  },
  {
    id: "logistics",
    eyebrow: "Optional torrefaction",
    headline: ["Thermal treatment", "comes later."],
    body: "Torrefaction and black pellet messaging belong after the finished pellet product, as an optional advanced product route.",
    data: "Finished pellets -> torrefaction option",
    tags: ["Extension", "Thermal Treatment"],
    align: "right",
  },
  {
    id: "energy",
    eyebrow: "Black wood pellet",
    headline: ["Advanced product", "after pellets."],
    body: "Black wood pellet is presented as a downstream technology product after the regular finished wood pellet line is complete.",
    data: "Finished pellet -> upgraded pellet",
    tags: ["Advanced Product", "After Unit 9"],
    align: "left",
  },
  {
    id: "circular",
    eyebrow: "Advanced bioenergy",
    headline: ["From wood.", "To pellet.", "To higher value."],
    body: "Built from responsible resources, shaped by technology, and guided by a pioneer mindset, AVP turns biomass into higher-value advanced bioenergy.",
    data: "Responsible resources → technology → global energy value",
    tags: ["Responsible Resources", "Renewable Energy", "Global Partners"],
    align: "center",
  },
];

export const COPY_VI: SectionCopy[] = [
  {
    id: "hero",
    eyebrow: "AVP Biomass",
    headline: ["Từ Phế Thải Gỗ", "Đến Năng Lượng Sạch"],
    body: "Viên nén sinh khối bền vững, được thiết kế cho hiệu suất và một tương lai xanh hơn. Năng lượng tái tạo. Trách nhiệm với tương lai.",
    tags: ["100% Tái Tạo"],
    align: "left",
  },
  {
    id: "forest",
    eyebrow: "Nguyên liệu gỗ đầu vào",
    headline: ["Phụ phẩm gỗ", "vào dây chuyền."],
    body: "Quy trình bắt đầu từ phụ phẩm gỗ, mảnh bìa, vỏ và dăm được thu gom từ nguồn chế biến gỗ có trách nhiệm.",
    data: "Phụ phẩm gỗ → bãi tiếp nhận",
    tags: ["Nguồn có trách nhiệm", "Phụ phẩm gỗ"],
    align: "left",
  },
  {
    id: "collection",
    eyebrow: "",
    headline: [],
    align: "left",
    hidden: true,
  },
  {
    id: "screening",
    eyebrow: "Cụm băm dăm gỗ",
    headline: ["Phụ phẩm thành", "dăm đồng nhất."],
    body: "Máy băm đồng nhất kích thước phụ phẩm gỗ đã tập kết thành dăm kiểm soát để đưa vào công đoạn nghiền.",
    data: "Phụ phẩm gỗ → băm dăm → dăm gỗ",
    tags: ["Unit 2", "Dây chuyền băm"],
    align: "left",
  },
  {
    id: "grinding",
    eyebrow: "Cụm nghiền ướt",
    headline: ["Nguyên liệu ướt", "được tinh chỉnh."],
    body: "Dăm gỗ được nghiền khi vẫn còn độ ẩm, tạo nguyên liệu nhỏ hơn trước khi đưa vào lưu trữ đệm.",
    data: "Dăm gỗ → nghiền ướt → hạt ướt",
    tags: ["Unit 3", "Nguyên liệu ướt"],
    align: "right",
  },
  {
    id: "drying",
    eyebrow: "Kho chứa đệm",
    headline: ["Dòng nguyên liệu", "được cân bằng."],
    body: "Sau nghiền ướt, nguyên liệu trung gian được giữ trong kho chứa đệm để cấp liệu ổn định cho công đoạn sấy.",
    data: "Hạt ướt → lưu trữ đệm",
    tags: ["Unit 4", "Cân bằng dòng liệu"],
    align: "left",
  },
  {
    id: "conditioning",
    eyebrow: "Cụm sấy",
    headline: ["Độ ẩm", "được kiểm soát."],
    body: "Nguyên liệu từ kho đệm đi vào cụm sấy, nơi độ ẩm được giảm về khoảng mục tiêu cho sản xuất viên nén ổn định.",
    data: "Sinh khối đệm → sấy → sinh khối khô",
    tags: ["Unit 5", "Kiểm soát độ ẩm"],
    align: "right",
  },
  {
    id: "pelletizing",
    eyebrow: "Cụm thu hồi",
    headline: ["Phần hữu dụng", "được thu hồi."],
    body: "Cụm thu hồi tách vật liệu khô sử dụng được khỏi bụi và phần sai kích thước trước bước nghiền khô cuối.",
    data: "Sinh khối khô → thu hồi → liệu khô sạch",
    tags: ["Unit 6", "Thu hồi vật liệu"],
    align: "left",
  },
  {
    id: "cooling",
    eyebrow: "Cụm nghiền khô",
    headline: ["Nguyên liệu khô", "được nghiền lại."],
    body: "Sinh khối khô sau thu hồi được nghiền lần hai để đạt độ đồng nhất hạt cần thiết trước khi ép viên.",
    data: "Liệu thu hồi → nghiền khô → liệu ép viên",
    tags: ["Unit 7", "Kích thước hạt cuối"],
    align: "right",
  },
  {
    id: "qc",
    eyebrow: "Cụm ép viên",
    headline: ["Áp lực", "tạo viên nén."],
    body: "Hạt khô đã chuẩn bị được nén qua máy ép viên để tạo thành viên nén gỗ đồng nhất và có mật độ cao.",
    data: "Liệu ép viên → máy ép → viên nén gỗ",
    tags: ["Unit 8", "Nén tạo hình"],
    align: "left",
  },
  {
    id: "packaging",
    eyebrow: "Cụm thành phẩm",
    headline: ["Viên nén hoàn thiện", "sẵn sàng xử lý."],
    body: "Viên nén gỗ thành phẩm được thu gom như sản phẩm cốt lõi của dây chuyền, sẵn sàng cho lưu kho, kiểm soát chất lượng hoặc xuất hàng.",
    data: "Viên nén gỗ → thành phẩm",
    tags: ["Unit 9", "Sản phẩm cốt lõi"],
    align: "right",
  },
  {
    id: "warehouse",
    eyebrow: "Hướng nâng cấp tùy chọn",
    headline: ["Bên ngoài", "dây chuyền lõi."],
    body: "Sau cụm thành phẩm, AVP có thể giới thiệu công nghệ nâng cấp giá trị như một phần mở rộng riêng, không thuộc chín cụm cơ bản.",
    data: "Thành phẩm → nâng cấp tùy chọn",
    tags: ["Mở rộng", "Tách khỏi dây chuyền lõi"],
    align: "left",
  },
  {
    id: "logistics",
    eyebrow: "Torrefaction tùy chọn",
    headline: ["Xử lý nhiệt", "diễn ra sau."],
    body: "Thông điệp torrefaction và viên nén đen thuộc tuyến sản phẩm nâng cao sau viên nén thành phẩm thông thường.",
    data: "Viên nén thành phẩm → tùy chọn torrefaction",
    tags: ["Mở rộng", "Xử lý nhiệt"],
    align: "right",
  },
  {
    id: "energy",
    eyebrow: "Viên nén gỗ đen",
    headline: ["Sản phẩm nâng cao", "sau viên nén."],
    body: "Viên nén gỗ đen được trình bày như sản phẩm công nghệ phía sau dây chuyền viên nén gỗ thông thường.",
    data: "Viên nén thành phẩm → viên nén nâng cấp",
    tags: ["Sản phẩm nâng cao", "Sau Unit 9"],
    align: "left",
  },
  {
    id: "circular",
    eyebrow: "Năng lượng sinh khối tiên tiến",
    headline: ["Từ gỗ.", "Đến viên nén.", "Đến giá trị cao hơn."],
    body: "Được xây dựng từ nguồn tài nguyên có trách nhiệm, định hình bởi công nghệ, và dẫn dắt bởi tư duy tiên phong, AVP biến sinh khối thành năng lượng sinh học tiên tiến giá trị cao.",
    data: "Tài nguyên trách nhiệm → công nghệ → giá trị năng lượng toàn cầu",
    tags: ["Tài Nguyên Trách Nhiệm", "Năng Lượng Tái Tạo", "Đối Tác Toàn Cầu"],
    align: "center",
  },
];

export function getCopy(locale: "en" | "vi"): SectionCopy[] {
  return locale === "vi" ? COPY_VI : COPY_EN;
}
